backend:
  name: github
  repo: nickk00324/full-service
  branch: main

media_folder: data/images

collections:
  - name: project
    label: Projects
    folder: data/projects
    media_folder: images/{{slug}}
    create: true
    editor:
      preview: false
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: description, label: Project Description, widget: markdown }
      - { name: additionalInfo, label: Additional Info, widget: markdown, required: false }
      - label: "Project Images"
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}