backend:
  name: github
  repo: nickk00324/full-service
  branch: main

media_library:
  name: cloudinary
  config:
    cloud_name: dspqphkii
    api_key: 612218668342215
    multiple: true

collections:
  - name: project
    label: Project
    folder: data/projects
    media_folder: assets/images
    create: true
    editor:
      preview: false
    fields:
      - { name: url, label: URL, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: description, label: Project Description, widget: markdown }
      - name: images
        label: Project Images
        widget: image