backend:
  name: github
  repo: nickk00324/full-service

media_folder: static/assets
public_folder: /assets

collections:
  - name: project
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }